### ISSUE TITLE
Bug: Sleep-time setting has wrong label

### ISSUE THREAD

**Issue by maqor** [z3r0c00l-2k/AquaDroid#61] opened 2021-04-13 15:42 UTC
If you open the settings, the field for setting your sleep time says "wake-up time" instead of sleep time. Both the fields for wake-up and sleep time have the same description text.

**Comment by manto89** [comment] 2021-07-08 17:55
I think this a duplicate of #34 
@z3r0c00l-2k

**Closed as completed** 2021-07-09 09:12 UTC
